version: '2.4'
services:

  rasa-server:
    image: rasa/rasa:3.6.19-full
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./custom.py:/app/custom.py
    - ./actions:/app/actions
    - ./data:/app/data
    - ./models:/app/models
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5005:5005'
    networks:
    - all

  rasa-actions-server:
    image: rasa/rasa-sdk:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"